server:
  port: 8001

spring:
  application:
    name: config-git-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bytegriffin/spring-cloud-sample/   
          search-paths: config-git-server-eureka/config-repo                         
          username:                         
          password:  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/