server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   #表示本服务是否是向注册中心注册自己（配置高可用的时候需要设置为true,也就是默认值）
    fetchRegistry: false        #是否去检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
